#!/bin/bash

# Check for the "install" command
if [ "$1" == "install" ]; then
  npm install --legacy-peer-deps
  if [ $? -eq 0 ]; then
    exit 0
  else
    exit 1
  fi
fi
# Check for the "test" command
if [ "$1" == "test" ]; then
  # rm -f testResults.txt
  # npx jest --verbose --json > jest_logs.txt 2>&1
  if [ $? -eq 0 ]; then
    # Parse testResults and return sum of all number values
    passed=0 #$(grep -oP 'Passed\s+\K\d+' testResults.txt | awk '{s+=$1} END {print s}')
    total=0 #$(grep -oP 'Total\s+\K\d+' testResults.txt | awk '{s+=$1} END {print s}')

    coverage=0

    echo "${passed}/${total} test cases passed. ${coverage}% line coverage achieved."
    exit 0
  else
    exit 1
  fi
fi

# Check for URL_FILE argument
if [ "$#" -ne 1 ]; then
  exit 1
fi

# Run the Node.js application with the provided URL_FILE
node dist/src/main.js "$1"